services:
  - type: web
    name: voting-project
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn voting_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: voting_project.settings
      - key: PYTHON_VERSION
        value: 3.10
